
   SET_THEME_FLAGS(  resFlagPaired  );
   DEFINE_IMAGE( bmpPause, wxImage( 16, 16 ), L"Pause");
   DEFINE_IMAGE( bmpPauseDisabled, wxImage( 16, 16 ), L"PauseDisabled");
   DEFINE_IMAGE( bmpPlay, wxImage( 16, 16 ), L"Play");
   DEFINE_IMAGE( bmpPlayDisabled, wxImage( 16, 16 ), L"PlayDisabled");
   DEFINE_IMAGE( bmpLoop, wxImage( 16, 16 ), L"Loop");
   DEFINE_IMAGE( bmpLoopDisabled, wxImage( 16, 16 ), L"LoopDisabled");
   DEFINE_IMAGE( bmpCutPreview, wxImage( 16, 16 ), L"CutPreview");
   DEFINE_IMAGE( bmpCutPreviewDisabled, wxImage( 16, 16 ), L"CutPreviewDisabled");
   DEFINE_IMAGE( bmpStop, wxImage( 16, 16 ), L"Stop");
   DEFINE_IMAGE( bmpStopDisabled, wxImage( 16, 16 ), L"StopDisabled");
   DEFINE_IMAGE( bmpRewind, wxImage( 16, 16 ), L"Rewind");
   DEFINE_IMAGE( bmpRewindDisabled, wxImage( 16, 16 ), L"RewindDisabled");
   DEFINE_IMAGE( bmpFFwd, wxImage( 16, 16 ), L"FFwd");
   DEFINE_IMAGE( bmpFFwdDisabled, wxImage( 16, 16 ), L"FFwdDisabled");
   DEFINE_IMAGE( bmpRecord, wxImage( 16, 16 ), L"Record");
   DEFINE_IMAGE( bmpRecordDisabled, wxImage( 16, 16 ), L"RecordDisabled");
   DEFINE_IMAGE( bmpRecordBeside, wxImage( 16, 16 ), L"RecordBeside");
   DEFINE_IMAGE( bmpRecordBesideDisabled, wxImage( 16, 16 ), L"RecordBesideDisabled");
   DEFINE_IMAGE( bmpRecordBelow, wxImage( 16, 16 ), L"RecordBelow");
   DEFINE_IMAGE( bmpRecordBelowDisabled, wxImage( 16, 16 ), L"RecordBelowDisabled");
   DEFINE_IMAGE( bmpScrub, wxImage( 18, 16 ), L"Scrub");
   DEFINE_IMAGE( bmpScrubDisabled, wxImage( 18, 16 ), L"ScrubDisabled");
   DEFINE_IMAGE( bmpSeek, wxImage( 26, 16 ), L"Seek");
   DEFINE_IMAGE( bmpSeekDisabled, wxImage( 26, 16 ), L"SeekDisabled");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpIBeam, wxImage( 27, 27 ), L"IBeam");
   DEFINE_IMAGE( bmpZoom, wxImage( 27, 27 ), L"Zoom");
   DEFINE_IMAGE( bmpEnvelope, wxImage( 27, 27 ), L"Envelope");
   DEFINE_IMAGE( bmpTimeShift, wxImage( 27, 27 ), L"TimeShift");
   DEFINE_IMAGE( bmpDraw, wxImage( 27, 27 ), L"Draw");
   DEFINE_IMAGE( bmpMulti, wxImage( 27, 27 ), L"Multi");
   DEFINE_IMAGE( bmpMic, wxImage( 25, 25 ), L"Mic");
   DEFINE_IMAGE( bmpSpeaker, wxImage( 25, 25 ), L"Speaker");

   SET_THEME_FLAGS(  resFlagPaired  );
   DEFINE_IMAGE( bmpZoomFit, wxImage( 27, 27 ), L"ZoomFit");
   DEFINE_IMAGE( bmpZoomFitDisabled, wxImage( 27, 27 ), L"ZoomFitDisabled");
   DEFINE_IMAGE( bmpZoomIn, wxImage( 27, 27 ), L"ZoomIn");
   DEFINE_IMAGE( bmpZoomInDisabled, wxImage( 27, 27 ), L"ZoomInDisabled");
   DEFINE_IMAGE( bmpZoomOut, wxImage( 27, 27 ), L"ZoomOut");
   DEFINE_IMAGE( bmpZoomOutDisabled, wxImage( 27, 27 ), L"ZoomOutDisabled");
   DEFINE_IMAGE( bmpZoomSel, wxImage( 27, 27 ), L"ZoomSel");
   DEFINE_IMAGE( bmpZoomSelDisabled, wxImage( 27, 27 ), L"ZoomSelDisabled");
   DEFINE_IMAGE( bmpZoomToggle, wxImage( 27, 27 ), L"ZoomToggle");
   DEFINE_IMAGE( bmpZoomToggleDisabled, wxImage( 27, 27 ), L"ZoomToggleDisabled");
   DEFINE_IMAGE( bmpCut, wxImage( 26, 24 ), L"Cut");
   DEFINE_IMAGE( bmpCutDisabled, wxImage( 26, 24 ), L"CutDisabled");
   DEFINE_IMAGE( bmpCopy, wxImage( 26, 24 ), L"Copy");
   DEFINE_IMAGE( bmpCopyDisabled, wxImage( 26, 24 ), L"CopyDisabled");
   DEFINE_IMAGE( bmpPaste, wxImage( 26, 24 ), L"Paste");
   DEFINE_IMAGE( bmpPasteDisabled, wxImage( 26, 24 ), L"PasteDisabled");
   DEFINE_IMAGE( bmpTrim, wxImage( 26, 24 ), L"Trim");
   DEFINE_IMAGE( bmpTrimDisabled, wxImage( 26, 24 ), L"TrimDisabled");
   DEFINE_IMAGE( bmpSilence, wxImage( 26, 24 ), L"Silence");
   DEFINE_IMAGE( bmpSilenceDisabled, wxImage( 26, 24 ), L"SilenceDisabled");
   DEFINE_IMAGE( bmpUndo, wxImage( 26, 24 ), L"Undo");
   DEFINE_IMAGE( bmpUndoDisabled, wxImage( 26, 24 ), L"UndoDisabled");
   DEFINE_IMAGE( bmpRedo, wxImage( 26, 24 ), L"Redo");
   DEFINE_IMAGE( bmpRedoDisabled, wxImage( 26, 24 ), L"RedoDisabled");

   SET_THEME_FLAGS(  resFlagPaired | resFlagNewLine  );
   DEFINE_IMAGE( bmpTnStartOn, wxImage( 27, 27 ), L"TnStartOn");
   DEFINE_IMAGE( bmpTnStartOnDisabled, wxImage( 27, 27 ), L"TnStartOnDisabled");
   DEFINE_IMAGE( bmpTnStartOff, wxImage( 27, 27 ), L"TnStartOff");
   DEFINE_IMAGE( bmpTnStartOffDisabled, wxImage( 27, 27 ), L"TnStartOffDisabled");
   DEFINE_IMAGE( bmpTnEndOn, wxImage( 27, 27 ), L"TnEndOn");
   DEFINE_IMAGE( bmpTnEndOnDisabled, wxImage( 27, 27 ), L"TnEndOnDisabled");
   DEFINE_IMAGE( bmpTnEndOff, wxImage( 27, 27 ), L"TnEndOff");
   DEFINE_IMAGE( bmpTnEndOffDisabled, wxImage( 27, 27 ), L"TnEndOffDisabled");
   DEFINE_IMAGE( bmpTnCalibrate, wxImage( 27, 27 ), L"TnCalibrate");
   DEFINE_IMAGE( bmpTnCalibrateDisabled, wxImage( 27, 27 ), L"TnCalibrateDisabled");
   DEFINE_IMAGE( bmpTnAutomateSelection, wxImage( 27, 27 ), L"TnAutomateSelection");
   DEFINE_IMAGE( bmpTnAutomateSelectionDisabled, wxImage( 27, 27 ), L"TnAutomateSelectionDisabled");
   DEFINE_IMAGE( bmpTnMakeTag, wxImage( 27, 27 ), L"TnMakeTag");
   DEFINE_IMAGE( bmpTnMakeTagDisabled, wxImage( 27, 27 ), L"TnMakeTagDisabled");
   DEFINE_IMAGE( bmpTnSelectSound, wxImage( 24, 24 ), L"TnSelectSound");
   DEFINE_IMAGE( bmpTnSelectSoundDisabled, wxImage( 24, 24 ), L"TnSelectSoundDisabled");
   DEFINE_IMAGE( bmpTnSelectSilence, wxImage( 24, 24 ), L"TnSelectSilence");
   DEFINE_IMAGE( bmpTnSelectSilenceDisabled, wxImage( 24, 24 ), L"TnSelectSilenceDisabled");
   DEFINE_IMAGE( bmpOptions, wxImage( 24, 24 ), L"Options");
   DEFINE_IMAGE( bmpOptionsDisabled, wxImage( 24, 24 ), L"OptionsDisabled");

   SET_THEME_FLAGS(  resFlagNone  );
   DEFINE_IMAGE( bmpLabelGlyph0, wxImage( 15, 23 ), L"LabelGlyph0");
   DEFINE_IMAGE( bmpLabelGlyph1, wxImage( 15, 23 ), L"LabelGlyph1");
   DEFINE_IMAGE( bmpLabelGlyph2, wxImage( 15, 23 ), L"LabelGlyph2");
   DEFINE_IMAGE( bmpLabelGlyph3, wxImage( 15, 23 ), L"LabelGlyph3");
   DEFINE_IMAGE( bmpLabelGlyph4, wxImage( 15, 23 ), L"LabelGlyph4");
   DEFINE_IMAGE( bmpLabelGlyph5, wxImage( 15, 23 ), L"LabelGlyph5");
   DEFINE_IMAGE( bmpLabelGlyph6, wxImage( 15, 23 ), L"LabelGlyph6");
   DEFINE_IMAGE( bmpLabelGlyph7, wxImage( 15, 23 ), L"LabelGlyph7");
   DEFINE_IMAGE( bmpLabelGlyph8, wxImage( 15, 23 ), L"LabelGlyph8");
   DEFINE_IMAGE( bmpLabelGlyph9, wxImage( 15, 23 ), L"LabelGlyph9");
   DEFINE_IMAGE( bmpLabelGlyph10, wxImage( 15, 23 ), L"LabelGlyph10");
   DEFINE_IMAGE( bmpLabelGlyph11, wxImage( 15, 23 ), L"LabelGlyph11");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpSyncLockSelTile, wxImage( 20, 22 ), L"SyncLockSelTile");
   DEFINE_IMAGE( bmpSyncLockTracksDown, wxImage( 20, 20 ), L"SyncLockTracksDown");
   DEFINE_IMAGE( bmpSyncLockTracksUp, wxImage( 20, 20 ), L"SyncLockTracksUp");
   DEFINE_IMAGE( bmpSyncLockTracksDisabled, wxImage( 20, 20 ), L"SyncLockTracksDisabled");
   DEFINE_IMAGE( bmpSyncLockIcon, wxImage( 12, 12 ), L"SyncLockIcon");
   DEFINE_IMAGE( bmpEditEffects, wxImage( 21, 20 ), L"EditEffects");
   DEFINE_IMAGE( bmpToggleScrubRuler, wxImage( 20, 20 ), L"ToggleScrubRuler");
   DEFINE_IMAGE( bmpHelpIcon, wxImage( 21, 21 ), L"HelpIcon");

   SET_THEME_FLAGS(  resFlagNone  );
   DEFINE_IMAGE( bmpPlayPointer, wxImage( 20, 20 ), L"PlayPointer");
   DEFINE_IMAGE( bmpPlayPointerPinned, wxImage( 20, 20 ), L"PlayPointerPinned");
   DEFINE_IMAGE( bmpRecordPointer, wxImage( 20, 20 ), L"RecordPointer");
   DEFINE_IMAGE( bmpRecordPointerPinned, wxImage( 20, 20 ), L"RecordPointerPinned");
   DEFINE_IMAGE( bmpGrabberDropLoc, wxImage( 20, 20 ), L"GrabberDropLoc");
   DEFINE_IMAGE( bmpSliderThumb, wxImage( 20, 20 ), L"SliderThumb");
   DEFINE_IMAGE( bmpSliderThumbHilited, wxImage( 20, 20 ), L"SliderThumbHilited");
   DEFINE_IMAGE( bmpSliderThumbRotated, wxImage( 20, 20 ), L"SliderThumbRotated");
   DEFINE_IMAGE( bmpSliderThumbRotatedHilited, wxImage( 20, 20 ), L"SliderThumbRotatedHilited");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpUpButtonExpand, wxImage( 96, 18 ), L"UpButtonExpand");
   DEFINE_IMAGE( bmpDownButtonExpand, wxImage( 96, 18 ), L"DownButtonExpand");
   DEFINE_IMAGE( bmpHiliteUpButtonExpand, wxImage( 96, 18 ), L"HiliteUpButtonExpand");
   DEFINE_IMAGE( bmpHiliteButtonExpand, wxImage( 96, 18 ), L"HiliteButtonExpand");
   DEFINE_IMAGE( bmpUpButtonExpandSel, wxImage( 96, 18 ), L"UpButtonExpandSel");
   DEFINE_IMAGE( bmpDownButtonExpandSel, wxImage( 96, 18 ), L"DownButtonExpandSel");
   DEFINE_IMAGE( bmpHiliteUpButtonExpandSel, wxImage( 96, 18 ), L"HiliteUpButtonExpandSel");
   DEFINE_IMAGE( bmpHiliteButtonExpandSel, wxImage( 96, 18 ), L"HiliteButtonExpandSel");

   SET_THEME_FLAGS(  resFlagNone  );
   DEFINE_IMAGE( bmpUpButtonLarge, wxImage( 48, 48 ), L"UpButtonLarge");
   DEFINE_IMAGE( bmpDownButtonLarge, wxImage( 48, 48 ), L"DownButtonLarge");
   DEFINE_IMAGE( bmpHiliteUpButtonLarge, wxImage( 48, 48 ), L"HiliteUpButtonLarge");
   DEFINE_IMAGE( bmpHiliteButtonLarge, wxImage( 48, 48 ), L"HiliteButtonLarge");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpMacUpButton, wxImage( 36, 36 ), L"MacUpButton");
   DEFINE_IMAGE( bmpMacDownButton, wxImage( 36, 36 ), L"MacDownButton");
   DEFINE_IMAGE( bmpMacHiliteUpButton, wxImage( 36, 36 ), L"MacHiliteUpButton");
   DEFINE_IMAGE( bmpMacHiliteButton, wxImage( 36, 36 ), L"MacHiliteButton");

   SET_THEME_FLAGS(  resFlagNone  );
   DEFINE_IMAGE( bmpUpButtonSmall, wxImage( 27, 27 ), L"UpButtonSmall");
   DEFINE_IMAGE( bmpDownButtonSmall, wxImage( 27, 27 ), L"DownButtonSmall");
   DEFINE_IMAGE( bmpHiliteUpButtonSmall, wxImage( 27, 27 ), L"HiliteUpButtonSmall");
   DEFINE_IMAGE( bmpHiliteButtonSmall, wxImage( 27, 27 ), L"HiliteButtonSmall");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpMacUpButtonSmall, wxImage( 27, 27 ), L"MacUpButtonSmall");
   DEFINE_IMAGE( bmpMacDownButtonSmall, wxImage( 27, 27 ), L"MacDownButtonSmall");
   DEFINE_IMAGE( bmpMacHiliteUpButtonSmall, wxImage( 27, 27 ), L"MacHiliteUpButtonSmall");
   DEFINE_IMAGE( bmpMacHiliteButtonSmall, wxImage( 27, 27 ), L"MacHiliteButtonSmall");

   SET_THEME_FLAGS(  resFlagInternal  );
   DEFINE_IMAGE( bmpRecoloredUpLarge, wxImage( 36, 36 ), L"RecoloredUpLarge");
   DEFINE_IMAGE( bmpRecoloredDownLarge, wxImage( 36, 36 ), L"RecoloredDownLarge");
   DEFINE_IMAGE( bmpRecoloredUpHiliteLarge, wxImage( 36, 36 ), L"RecoloredUpHiliteLarge");
   DEFINE_IMAGE( bmpRecoloredHiliteLarge, wxImage( 36, 36 ), L"RecoloredHiliteLarge");
   DEFINE_IMAGE( bmpRecoloredUpSmall, wxImage( 27, 27 ), L"RecoloredUpSmall");
   DEFINE_IMAGE( bmpRecoloredDownSmall, wxImage( 27, 27 ), L"RecoloredDownSmall");
   DEFINE_IMAGE( bmpRecoloredUpHiliteSmall, wxImage( 27, 27 ), L"RecoloredUpHiliteSmall");
   DEFINE_IMAGE( bmpRecoloredHiliteSmall, wxImage( 27, 27 ), L"RecoloredHiliteSmall");

   SET_THEME_FLAGS(  resFlagCursor  );
   DEFINE_IMAGE( bmpIBeamCursor, wxImage( 32, 32 ), L"IBeamCursor");
   DEFINE_IMAGE( bmpCrosshairCursor, wxImage( 32, 32 ), L"CrosshairCursor");
   DEFINE_IMAGE( bmpDrawCursor, wxImage( 32, 32 ), L"DrawCursor");
   DEFINE_IMAGE( bmpEnvCursor, wxImage( 32, 32 ), L"EnvCursor");
   DEFINE_IMAGE( bmpTimeCursor, wxImage( 32, 32 ), L"TimeCursor");
   DEFINE_IMAGE( bmpZoomInCursor, wxImage( 32, 32 ), L"ZoomInCursor");
   DEFINE_IMAGE( bmpZoomOutCursor, wxImage( 32, 32 ), L"ZoomOutCursor");
   DEFINE_IMAGE( bmpLabelCursorLeft, wxImage( 32, 32 ), L"LabelCursorLeft");
   DEFINE_IMAGE( bmpLabelCursorRight, wxImage( 32, 32 ), L"LabelCursorRight");
   DEFINE_IMAGE( bmpDisabledCursor, wxImage( 32, 32 ), L"DisabledCursor");
   DEFINE_IMAGE( bmpBottomFrequencyCursor, wxImage( 32, 32 ), L"BottomFrequencyCursor");
   DEFINE_IMAGE( bmpTopFrequencyCursor, wxImage( 32, 32 ), L"TopFrequencyCursor");
   DEFINE_IMAGE( bmpBandWidthCursor, wxImage( 32, 32 ), L"BandWidthCursor");
   DEFINE_IMAGE( bmpSubViewsCursor, wxImage( 32, 32 ), L"SubViewsCursor");

   SET_THEME_FLAGS(  resFlagNewLine  );
   DEFINE_IMAGE( bmpAudacityLogo48x48, wxImage( 48, 48 ), L"AudacityLogo48x48");
